// Package server bridges the transport-agnostic internal/raft package to
// gRPC: it implements raft.Transport using generated RaftService clients,
// and hosts both the RaftService and KVService gRPC servers.
//
// NOTE ON GENERATED CODE: this file imports proto/raftpb and proto/kvpb,
// which are generated by scripts/generate.sh (protoc-gen-go +
// protoc-gen-go-grpc). They are not present until you run that script -
// see README "Setup" for exact commands. This package therefore will not
// compile until generation has been run; internal/raft, internal/storage,
// and internal/kv compile independently of it.
package server

import (
	"context"
	"fmt"
	"sync"

	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"

	"github.com/salmanabdi-dev/distributed-kv/internal/raft"
	"github.com/salmanabdi-dev/distributed-kv/proto/raftpb"
)

// GRPCTransport implements raft.Transport over persistent gRPC connections,
// one per peer, established lazily and reused for the process lifetime.
// Reusing connections (rather than dialing per RPC) matters a great deal
// for sustained throughput: TCP/TLS/HTTP2 setup cost would otherwise be
// paid on every single AppendEntries call.
type GRPCTransport struct {
	mu    sync.Mutex
	conns map[string]*grpc.ClientConn // peerID -> conn
	addrs map[string]string           // peerID -> raft address
}

func NewGRPCTransport(peerRaftAddrs map[string]string) *GRPCTransport {
	return &GRPCTransport{
		conns: make(map[string]*grpc.ClientConn),
		addrs: peerRaftAddrs,
	}
}

func (t *GRPCTransport) client(peerID string) (raftpb.RaftServiceClient, error) {
	t.mu.Lock()
	defer t.mu.Unlock()

	if conn, ok := t.conns[peerID]; ok {
		return raftpb.NewRaftServiceClient(conn), nil
	}
	addr, ok := t.addrs[peerID]
	if !ok {
		return nil, fmt.Errorf("transport: unknown peer %q", peerID)
	}
	// WithTransportCredentials(insecure.NewCredentials()) since Raft/gRPC
	// traffic here runs on a private Docker network; see README
	// "Limitations" for the production TLS recommendation.
	conn, err := grpc.NewClient(addr,
		grpc.WithTransportCredentials(insecure.NewCredentials()),
	)
	if err != nil {
		return nil, err
	}
	t.conns[peerID] = conn
	return raftpb.NewRaftServiceClient(conn), nil
}

// Close closes all cached peer connections. It is safe to call more than
// once; after Close, future RPCs may lazily create fresh connections if the
// transport is reused.
func (t *GRPCTransport) Close() error {
	t.mu.Lock()
	conns := t.conns
	t.conns = make(map[string]*grpc.ClientConn)
	t.mu.Unlock()

	var firstErr error
	for _, conn := range conns {
		if err := conn.Close(); err != nil && firstErr == nil {
			firstErr = err
		}
	}
	return firstErr
}

func (t *GRPCTransport) RequestVote(ctx context.Context, peerID string, req *raft.RequestVoteRequest) (*raft.RequestVoteResponse, error) {
	c, err := t.client(peerID)
	if err != nil {
		return nil, err
	}
	resp, err := c.RequestVote(ctx, &raftpb.RequestVoteRequest{
		Term:         req.Term,
		CandidateId:  req.CandidateID,
		LastLogIndex: req.LastLogIndex,
		LastLogTerm:  req.LastLogTerm,
	})
	if err != nil {
		return nil, err
	}
	return &raft.RequestVoteResponse{Term: resp.Term, VoteGranted: resp.VoteGranted}, nil
}

func (t *GRPCTransport) AppendEntries(ctx context.Context, peerID string, req *raft.AppendEntriesRequest) (*raft.AppendEntriesResponse, error) {
	c, err := t.client(peerID)
	if err != nil {
		return nil, err
	}
	resp, err := c.AppendEntries(ctx, &raftpb.AppendEntriesRequest{
		Term:             req.Term,
		LeaderId:         req.LeaderID,
		PrevLogIndex:     req.PrevLogIndex,
		PrevLogTerm:      req.PrevLogTerm,
		Entries:          toPBEntries(req.Entries),
		LeaderCommit:     req.LeaderCommit,
		LeaderClientAddr: req.LeaderClientAddr,
	})
	if err != nil {
		return nil, err
	}
	return &raft.AppendEntriesResponse{
		Term:          resp.Term,
		Success:       resp.Success,
		ConflictTerm:  resp.ConflictTerm,
		ConflictIndex: resp.ConflictIndex,
	}, nil
}

func (t *GRPCTransport) InstallSnapshot(ctx context.Context, peerID string, req *raft.InstallSnapshotRequest) (*raft.InstallSnapshotResponse, error) {
	c, err := t.client(peerID)
	if err != nil {
		return nil, err
	}
	resp, err := c.InstallSnapshot(ctx, &raftpb.InstallSnapshotRequest{
		Term:              req.Term,
		LeaderId:          req.LeaderID,
		LastIncludedIndex: req.LastIncludedIndex,
		LastIncludedTerm:  req.LastIncludedTerm,
		Data:              req.Data,
	})
	if err != nil {
		return nil, err
	}
	return &raft.InstallSnapshotResponse{Term: resp.Term}, nil
}

func toPBEntries(entries []raft.Entry) []*raftpb.LogEntry {
	out := make([]*raftpb.LogEntry, len(entries))
	for i, e := range entries {
		out[i] = &raftpb.LogEntry{
			Index:           e.Index,
			Term:            e.Term,
			Type:            raftpb.EntryType(e.Type),
			Key:             e.Key,
			Value:           e.Value,
			ClientRequestId: e.ClientRequestID,
		}
	}
	return out
}

func fromPBEntries(entries []*raftpb.LogEntry) []raft.Entry {
	out := make([]raft.Entry, len(entries))
	for i, e := range entries {
		out[i] = raft.Entry{
			Index:           e.Index,
			Term:            e.Term,
			Type:            raft.EntryType(e.Type),
			Key:             e.Key,
			Value:           e.Value,
			ClientRequestID: e.ClientRequestId,
		}
	}
	return out
}
